# Generated by Django 4.2.13 on 2026-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrequest",
            name="priority",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("HIGH", "High"), ("URGENT", "Urgent")],
                default="NORMAL",
                max_length=20,
            ),
        ),
    ]
